### ISSUE TITLE
"ImportError: Permission denied" on CygWin on "import _cffi_backend as backend"

### ISSUE THREAD

**Issue by andy-maier** [theacodes/cmarkgfm#23] opened 2020-03-15 20:41 UTC
When trying to install cmarkgfm 0.4.2 on Cygwin, we get this error in Appveyor (link to the build for some Python versions: https://ci.appveyor.com/project/KSchopmeyer/pywbemtools/builds/31482928):

```
Collecting cmarkgfm>=0.4.2
  Downloading cmarkgfm-0.4.2.tar.gz (133 kB)
    ERROR: Command errored out with exit status 1:
     command: /cygdrive/c/projects/pywbemtools/.tox/cygwin64_py38/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5zucu9ti/cmarkgfm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5zucu9ti/cmarkgfm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-5zucu9ti/cmarkgfm/pip-egg-info
         cwd: /tmp/pip-install-5zucu9ti/cmarkgfm/
    Complete output (27 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5zucu9ti/cmarkgfm/setup.py", line 27, in <module>
        setup(
      File "/cygdrive/c/projects/pywbemtools/.tox/cygwin64_py38/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/cygdrive/c/projects/pywbemtools/.tox/cygwin64_py38/lib/python3.8/site-packages/setuptools/dist.py", line 424, in __init__
        _Distribution.__init__(self, {
      File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/cygdrive/c/projects/pywbemtools/.tox/cygwin64_py38/lib/python3.8/site-packages/setuptools/dist.py", line 706, in finalize_options
        ep.load()(self)
      File "/cygdrive/c/projects/pywbemtools/.tox/cygwin64_py38/lib/python3.8/site-packages/setuptools/dist.py", line 713, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-install-5zucu9ti/cmarkgfm/.eggs/cffi-1.14.0-py3.8-cygwin-3.1.4-x86_64.egg/cffi/setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/tmp/pip-install-5zucu9ti/cmarkgfm/.eggs/cffi-1.14.0-py3.8-cygwin-3.1.4-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/tmp/pip-install-5zucu9ti/cmarkgfm/.eggs/cffi-1.14.0-py3.8-cygwin-3.1.4-x86_64.egg/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/cmarkgfm/build_cmark.py", line 72, in <module>
        ffibuilder = cffi.FFI()
      File "/tmp/pip-install-5zucu9ti/cmarkgfm/.eggs/cffi-1.14.0-py3.8-cygwin-3.1.4-x86_64.egg/cffi/api.py", line 48, in __init__
        import _cffi_backend as backend
    ImportError: Permission denied
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
The same combination of packages and versions installs fine on Linux (Travis) and on native Windows (Appveyor). It fails on CygWIn (Appveyor)

I also ran this with the order of statements in the requirements file changed such that the referencing package came first and the referenced packages afterwards  (specifically: cffi after cmarkgfm), but the issue showed up in the exact same way. I only tried Python 3.7 and 3.8 so far; the issue happens in both versions.

**Comment by theacodes** [comment] 2020-11-21 22:21
I don't know how to properly support cygwin for this, so if anyone wants to offer expertise that would be grea.t

**Comment by theacodes** [comment] 2020-11-21 22:46
Closing as a duplicate of #13

**Closed by theacodes** 2020-11-21 22:46 UTC
Labels: help wanted
